blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import  post_create, post_list, post_details, post_update,post_delete,BlogPostLike

urlpatterns = [
    path('details/<int:id>', post_details, name='post_details'),
    path('blogpost-like/<int:id>', BlogPostLike, name="blogpost_like"),
    path('create',post_create, name="post_create"),
    path('list/',post_list , name="post_list"),
    path('update/<int:id>', post_update ,name="post_update"),
    path('delete/<int:id>', post_delete ,name="post_delete"),
    
     
    
  
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("users.urls")),
    path('blog/',include("blog.urls")),
    path('accounts/',include("django.contrib.auth.urls")),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import pre_save

from blogApp.util import unique_slug_generator
# from .models import Category


# Create your models here.

class Category(models.Model):
    CATEGORY_CHOICES=[
        ( 'FrontEnd','FE'),
        ('BackEnd','BE' ),
        ('FullStack','FS' ),
    ]
    name=models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    CATEGORY_CHOICES=[
        ( 'FrontEnd','FrontEnd'),
        ('BackEnd','BackEnd' ),
        ('FullStack','FullStack' ),
    ]
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=3000)
    image=models.ImageField(blank=True, upload_to='post_images')
    author=models.ForeignKey(User ,on_delete=models.CASCADE)
    category=models.CharField(max_length=100, choices=CATEGORY_CHOICES,default="FS")
    likes=models.ManyToManyField(User,related_name='blogpost_like', blank=True)
    
  
    def __str__(self):
        return self.title
    @property
    def number_of_likes(self):
        return self.likes.all().count()
    

 

class Comment(models.Model): 
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(User, on_delete=models.CASCADE) 
    body = models.TextField(blank=True) 
    created = models.DateTimeField(auto_now_add=True , blank=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 

    class Meta: 
        ordering = ('created',) 

    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post) 
    

blog/forms.py
from django import forms
from .models import  Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        # fields=["title","content","image","category"]
        exclude=['author','likes']
        
        
        widgets={
            "title":forms.TextInput(attrs={"class":"form-control",'placeHolder':'Name'}),
            "content":forms.Textarea(attrs={"class":"form-control"}),
            "category":forms.Select(attrs={"class":"form-control"}),
        }
        
        
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

blog/views.py
from django.urls import reverse
from multiprocessing import context
from unicodedata import category
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .forms import  PostForm, CommentForm
from django.shortcuts import redirect, render
from .models import Category, Post
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
# Create your views here.

def post_list(request):
   print(User.username)
   posts=Post.objects.all()   
   context={
      "posts":posts
      
   }
   return render(request, 'blog/post_list.html',context)

def BlogPostLike(request, id):
    post = get_object_or_404(Post, id=request.POST.get('blogpost_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        print("number_of_likes")

    return HttpResponseRedirect(reverse('post_details', args=[str(id)]))
 
 

 

def post_create(request):
   form=PostForm(request.POST or None)
   
   if request.method=="POST":
      form=PostForm(request.POST, request.FILES)
      if form.is_valid() :
         new_creator=form.save(commit=False)
         new_creator.author =request.user         
         new_creator.save()
         form.save_m2m()
         
         return redirect("post_list")
         
   context={
      "form":form
   }
   return render(request,"blog/post_create.html",context)





def post_details(request, id):
    template_name = 'blog/post_details.html'
    post = get_object_or_404(Post, id=id)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            new_comment.name= request.user
            
            # new_comment.email=request.email
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})
    
def post_update(request,id):
   post=Post.objects.get(id=id)
   form=PostForm(instance=post)
   if request.method=="POST":
      form=PostForm(request.POST, request.FILES, instance=post )
      if form.is_valid():
         form.save()
         return redirect("post_list")
   context={
      "form":form
   }
   return render(request,"blog/post_update.html", context)   

def post_delete(request,id):
   post=Post.objects.get(id=id)
   if request.method=="POST":
      post.delete()
      return redirect("post_list")
   context={
      "post":post
   }
   return render(request,"blog/post_delete.html",context) 
    

    
    

blog/templates/blog/post_create.html
{% extends 'base.html' %} {% block content %} 
<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h3>Blog Post</h3>
        <hr />
        <form action="" method="POST" enctype="multipart/form-data" >
          {% csrf_token %} {{form.as_p}}
         
          <!-- <input
            type="hidden"
            name="csrfmiddlewaretoken"
            value="sFWVvXX75nJ8R5T0aemZ1LyfuHWyuU8jyDK2FshjxHqsVfc2TgwZkKAnfnns9UR6"
          />

          <div id="div_id_title" class="form-group">
            <label for="id_title" class="requiredField">
              Title<span class="asteriskField">*</span>
            </label>
            <div class="">{{form.title}}</div>
          </div>
          <div id="div_id_content" class="form-group">
            <label for="id_content" class="requiredField">
              Content<span class="asteriskField">*</span>
            </label>
            <div class="">
              {{form.content}}
              <!-- <textarea
                name="content"
                cols="40"
                rows="10"
                class="textarea form-control"
                required
                id="id_content"
              ></textarea> -->
            <!-- </div>
          </div>
          <div id="div_id_image" class="form-group">
            <label for="id_image" class="requiredField">
              Image<span class="asteriskField">*</span>
            </label>
            <div class="">
              {{form.image}} -->
              <!-- <input
                type="file"
                name="image"
                accept="image/*"
                class="clearablefileinput form-control-file"
                id="id_image"
              /> -->
            </div>
          </div>
          <!-- <div id="div_id_category" class="form-group">
            <label for="id_category" class="requiredField">
              Category<span class="asteriskField">*</span>
            </label>
            <div class="">
              <select
                name="category"
                class="select form-control"
                id="id_category"
              >
                <option value="fe">Frontend</option>
                <option value="be">Backend</option>
                <option value="fs">Fullstack</option>
              </select>
            </div>
          </div>
          <div id="div_id_status" class="form-group">
            <label for="id_status" class="requiredField">
              Status<span class="asteriskField">*</span>
            </label>
            <div class="">
              <select name="status" class="select form-control" id="id_status">
                <option value="d">Draft</option>
                <option value="p">Published</option>
              </select>
            </div>
          </div> -->

          <br /> 
          <button type="submit" class="btn btn-primary btn-lg">Post</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h3>Blog Post</h3>
        <hr />
        <form action="" method="POST">
          <p>Are You Sure Delete
          <h3>{{student.first_name}}</h3>
          </p>
          {% csrf_token %}
          <input type="submit" value="Yes" />
        </form>
        <a href="{% url 'post_list'%}">
          <input type="submit" value="Cancel" />
        </a>

      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/blog/post_details.html
{% extends 'base.html' %} {% block content %}
<div class="container">

  <div class="container">

    <div class="container card" style="width: 40rem;">
      <img src="../../../media/{{post.image}}" class="card-img-top" alt="post_image">
      <div class="card-body">
        <h2 class="card-title">{{post.title}}</h2>
        <hr>
        <div>
          <span><i class="far fa-comment-alt ml-2"></i></i> {{ comments.count }} comments</span>

          <span class="float-right"> <small>Posted {{comment.created}}</small> </span>
        </div>
        <hr>
        <p class="card-text">{{ post.content }}</p>
        <hr>
        <div>
          <h4>Enjoy this post? Give it a LIKE!!</h4>
        </div>

        <div>

          {% if user.is_authenticated %}
          <form action="{% url 'blogpost_like' post.id %}" method="POST">
            {% csrf_token %}

            {% if post_is_liked %}
            <button type="submit" name="blogpost_id" value="{{post.id}}" class="btn btn-info">Unlike</button>
            {% else %}
            <button type="submit" name="blogpost_id" value="{{post.id}}" class="btn btn-info">Like</button>
            {% endif %}
          </form>
          {% else %}
          <a class="btn btn-outline-info" href="{% url 'login' %}?next={{request.path}}">Log in to like this
            article!</a><br>
          {% endif %}
          <strong class="text-secondary">{{ number_of_likes }} Like</strong>

          <hr>
          {% if request.user.is_authenticated %}
          <!--  -->
          <h4>Leave a comment below</h4>

          {% if new_comment %}
          <div class="alert alert-success" role="alert">
            Your comment is awaiting moderation
          </div>
          {% else %}
          <form method="post" style="margin-top: 1.3em">
            {{ comment_form.body }} {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-primary btn-lg">SEND</button>
          </form>
          {% endif %}

          {% endif %}

          <hr>
          {% if request.user.is_authenticated %} {% if request.user == post.author %}

          <a href="/blog/update/{{ post.id }}"><button type="submit" class="btn btn-primary btn-lg">EDIT</button></a>
          <a href="/blog/delete/{{ post.id }}"><button type="submit" class="btn btn-primary btn-lg">DELETE</button> </a>
          {% endif %} {% endif %}

          <h4>Comments</h4>








          {% for comment in comments %}

          <div>
            <p>
              <small><b>Comment by {{comment.name}}</b></small> - <small> {{comment.created}}
              </small>
            </p>
            <p>
              {{comment.body}}

            </p>
          </div>
          <hr>
          {% endfor %}



        </div>

      </div>

      <div class="m-3">

      </div>

    </div>




    {% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %} {% block navcontent %}
<ul class="navbar-nav mt-2 mt-lg-0">
  {% if user.is_authenticated %}

  <li class="nav-item">
    <a class="nav-link" href="{% url 'profile' %}">{{post.title}}</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'post_create' %}">Create New Post</a>
  </li>
  {% else%}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'login' %}">Login</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href=" {% url 'register' %} ">Register</a>
  </li>
  {% endif %}
</ul>

{% endblock navcontent %}{% block content %}

<link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" />
<div class="container blog-page">
  <div class="row clearfix">
    {% for post in posts %}
    <div class="col-lg-4 col-md-12 mb-4 mt-4">

      <div class="card single_post">
        <div class="header"></div>
        <div style="align-items: center; justify-content: center; text-align: center;" class="body">
          <h3 class="m-t-0 m-b-5">
            <a href="blog_details.html">{{post.title}}</a>
          </h3>
          <img class="rounded-circle article-img" width="100px" src="{{ post.author.profile.image.url }}">
          <ul style="list-style-type: none;" class="meta">

            <li>

              <a href="javascript:void(0);"><i class="zmdi zmdi-account col-blue"></i>Posted By: {{post.author}}</a>
            </li>
            <li>
              <a href="javascript:void(0);"><i class="zmdi zmdi-label col-amber"></i>Category: {{post.category}}</a>
            </li>

          </ul>
        </div>
        <div class="body">
          <div class="img-post m-b-15">
            <center>
              <img width="300" height="200" src="../../../media/{{post.image}}" alt="{{post.image}}" />
            </center>
            <!-- <div style="text-align: center;" class="social_share">
              <button class="btn btn-primary btn-icon btn-icon-mini btn-round">
                <i class="zmdi zmdi-facebook"></i>
              </button>
              <button class="btn btn-primary btn-icon btn-icon-mini btn-round">
                <i class="zmdi zmdi-twitter"></i>
              </button>
              <button class="btn btn-primary btn-icon btn-icon-mini btn-round">
                <i class="zmdi zmdi-instagram"></i>
              </button>
            </div> -->
          </div>
          <p>{{post.content}}</p>
          <a href="/blog/details/{{ post.id }}" title="read more" class="btn btn-round btn-info">Read More</a>
        </div>
      </div>

    </div>
    <br>
    {% endfor %}
  </div>
</div>
</div>

{% endblock content %}

blog/templates/blog/post_update.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h3>Blog Post</h3>
        <hr />
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{form.as_p}}
          <!-- <input
            type="hidden"
            name="csrfmiddlewaretoken"
            value="sFWVvXX75nJ8R5T0aemZ1LyfuHWyuU8jyDK2FshjxHqsVfc2TgwZkKAnfnns9UR6"
          />

          <div id="div_id_title" class="form-group">
            <label for="id_title" class="requiredField">
              Title<span class="asteriskField">*</span>
            </label>
            <div class="">{{form.title}}</div>
          </div>
          <div id="div_id_content" class="form-group">
            <label for="id_content" class="requiredField">
              Content<span class="asteriskField">*</span>
            </label>
            <div class="">
              {{form.content}}
              <!-- <textarea
                name="content"
                cols="40"
                rows="10"
                class="textarea form-control"
                required
                id="id_content"
              ></textarea> -->
            <!-- </div>
          </div>
          <div id="div_id_image" class="form-group">
            <label for="id_image" class="requiredField">
              Image<span class="asteriskField">*</span>
            </label>
            <div class="">
              {{form.image}} -->
              <!-- <input
                type="file"
                name="image"
                accept="image/*"
                class="clearablefileinput form-control-file"
                id="id_image"
              /> -->
            </div>
          </div>
          <!-- <div id="div_id_category" class="form-group">
            <label for="id_category" class="requiredField">
              Category<span class="asteriskField">*</span>
            </label>
            <div class="">
              <select
                name="category"
                class="select form-control"
                id="id_category"
              >
                <option value="fe">Frontend</option>
                <option value="be">Backend</option>
                <option value="fs">Fullstack</option>
              </select>
            </div>
          </div>
          <div id="div_id_status" class="form-group">
            <label for="id_status" class="requiredField">
              Status<span class="asteriskField">*</span>
            </label>
            <div class="">
              <select name="status" class="select form-control" id="id_status">
                <option value="d">Draft</option>
                <option value="p">Published</option>
              </select>
            </div>
          </div> -->

          <br /> -->
          <button type="submit" class="btn btn-outline-info">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}